version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  prepare:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  build:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - build

  lint:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn lint

  package:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn package

workflows:
  version: 2
  build-test:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - lint:
          requires:
            - prepare
      - package:
          requires:
            - build
            - lint
          filters:
            branches:
              only:
                - master
