name: "Deploy"

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: "Build"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: action/setup-node@v3
        with:
          node-version: ".tool-version"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
  bump-version:
    name: "Bump up to the new version"
    runs-on: ubuntu-latest
    needs: build
    outputs:
      tag: ${{ steps.create-tag.outputs.new_tag }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0
      - name: "Bump version and create tag"
        id: create-tag
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: "v"
          MAJOR_STRING_TOKEN: breaking
          MINOR_STRING_TOKEN: feature
          PATCH_STRING_TOKEN: fix
  release-version:
    name: "Release new version"
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0
      - name: "Create a release"
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: Release ${{ needs.bump-version.outputs.tag }}
          tag_name: refs/tags/${{ needs.bump-version.outputs.tag }}
